## Задание 1.

Прочитать данные
`https://raw.githubusercontent.com/yakushinav/omo/main/data/movies.csv`

Имена столбцов
```
['color', 'director_name', 'num_critic_for_reviews', 'duration',
                'gross', 'movie_title', 'num_user_for_reviews', 'country',
                'cotent_rating', 'budget', 'title_year', 'imdb_score', 'genre']
```

In [26]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/yakushinav/omo/main/data/movies.csv',
                 header=None,
                 sep='|',
                 names=['color', 'director_name', 'num_critic_for_reviews', 'duration',
                'gross', 'movie_title', 'num_user_for_reviews', 'country',
                'cotent_rating', 'budget', 'title_year', 'imdb_score', 'genre'])
df.head()

,color,director_name,num_critic_for_reviews,duration,gross,movie_title,num_user_for_reviews,country,cotent_rating,budget,title_year,imdb_score,genre
0,Color,James Cameron,723.0,178.0,760505847.0,Avatar,3054.0,USA,PG-13,"237,000,000.0",2009.0,7.9,Action
1,Color,Gore Verbinski,302.0,169.0,309404152.0,Pirates of the Caribbean: At World's End,1238.0,USA,PG-13,"300,000,000.0",2007.0,7.1,Action
2,Color,Sam Mendes,602.0,148.0,200074175.0,Spectre,994.0,UK,PG-13,"245,000,000.0",2015.0,6.8,Action
3,Color,Christopher Nolan,813.0,164.0,448130642.0,The Dark Knight Rises,2701.0,USA,PG-13,"250,000,000.0",2012.0,8.5,Action
4,?,Doug Walker,?,?,?,Star Wars: Episode VII - The Force Awakens ...,?,?,?,?,?,7.1,Documentary

## Задание 2

Прочитать данные `https://raw.githubusercontent.com/yakushinav/omo/main/data/playstore.xlsx`.

Для столбца `Last_Updated` установить формат `дата_и_время`.

In [31]:
import pandas as pd
df = pd.read_excel('https://raw.githubusercontent.com/yakushinav/omo/main/data/playstore.xlsx')
df['Last_Updated'] = pd.to_datetime(df['Last_Updated'])
#df.dtypes
df.head()

,Unnamed: 0,App,Category,Rating,Installs,Type,Price,Content_ID,Genres,Last_Updated
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,"10,000+",Free,0,101,Art & Design,2018-01-07
1,1,Coloring book moana,ART_AND_DESIGN,3.9,"500,000+",Free,0,101,Art & Design;Pretend Play,2018-01-15
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,"5,000,000+",Free,0,101,Art & Design,2018-08-01
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,"50,000,000+",Free,0,102,Art & Design,2018-06-08
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,"100,000+",Free,0,101,Art & Design;Creativity,2018-06-20

## Задание 3

Прочитать данные `https://raw.githubusercontent.com/yakushinav/omo/main/data/artists.json`.

Выполнить сохранение в формат CSV. Прочитать полученный файл. Сравнить с исходным.

In [39]:
import pandas as pd
artist = pd.read_json('https://raw.githubusercontent.com/yakushinav/omo/main/data/artists.json')
#artist.head()
artist.to_csv('artist_csv.csv')
pd.read_csv('artist_csv.csv').head()

,Unnamed: 0,name,years,genre,nationality,bio
0,0,Amedeo Modigliani,1884 - 1920,Expressionism,Italian,"[{'full name': 'Amedeo Clemente Modigliani', '..."
1,1,Vasiliy Kandinskiy,1866 - 1944,"Expressionism,Abstractionism",Russian,[{'full name': 'Wassily Wassilyevich Kandinsky...
2,2,Diego Rivera,1886 - 1957,"Social Realism,Muralism",Mexican,[{'full name': 'Diego María de la Concepción J...
3,3,Claude Monet,1840 - 1926,Impressionism,French,"[{'full name': 'Oscar-Claude Monet', 'pronunci..."
4,4,Rene Magritte,1898 - 1967,"Surrealism,Impressionism",Belgian,[{'full name': 'René François Ghislain Magritt...